//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DasBankReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DasBankReference.IOnurBankService")]
    public interface IOnurBankService
    {
        
        [System.ServiceModel.OperationContractAttribute(
            Action="http://tempuri.org/IOnurBankService/GetData", 
            ReplyAction="http://tempuri.org/IOnurBankService/GetDataResponse")]
        string GetData(int value);

        
        [System.ServiceModel.OperationContractAttribute(
            Action="http://tempuri.org/IOnurBankService/GetData", 
            ReplyAction="http://tempuri.org/IOnurBankService/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);

        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnurBankService/GetDataButEmulateServerAbort", ReplyAction="http://tempuri.org/IOnurBankService/GetDataButEmulateServerAbortResponse")]
        string GetDataButEmulateServerAbort(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnurBankService/GetDataButEmulateServerAbort", ReplyAction="http://tempuri.org/IOnurBankService/GetDataButEmulateServerAbortResponse")]
        System.Threading.Tasks.Task<string> GetDataButEmulateServerAbortAsync(int value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IOnurBankServiceChannel : DasBankReference.IOnurBankService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class OnurBankServiceClient : System.ServiceModel.ClientBase<DasBankReference.IOnurBankService>, DasBankReference.IOnurBankService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public OnurBankServiceClient() : 
                base(OnurBankServiceClient.GetDefaultBinding(), OnurBankServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IOnurBankService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OnurBankServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(OnurBankServiceClient.GetBindingForEndpoint(endpointConfiguration), OnurBankServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OnurBankServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(OnurBankServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OnurBankServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(OnurBankServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OnurBankServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public string GetData(int value)
        {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value)
        {
            return base.Channel.GetDataAsync(value);
        }
        
        public string GetDataButEmulateServerAbort(int value)
        {
            return base.Channel.GetDataButEmulateServerAbort(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataButEmulateServerAbortAsync(int value)
        {
            return base.Channel.GetDataButEmulateServerAbortAsync(value);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IOnurBankService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IOnurBankService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:2937/DasOnurBankService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return OnurBankServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IOnurBankService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return OnurBankServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IOnurBankService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IOnurBankService,
        }
    }
}
